---
verifier:
  name: inspec

driver:
  name: openstack
  flavor_ref: 'm1.large'
  user_data: userdata.txt

driver_config:
  server_name: node1

provisioner:
  name: chef_zero
  roles_path: test/integration/roles
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  attributes:
    yum:
      epel:
        baseurl: http://epel.osuosl.org/7/$basearch
        gpgkey: http://epel.osuosl.org/RPM-GPG-KEY-EPEL-7
    ceph:
      keyring:
        mon: '/etc/ceph/$cluster.mon.keyring'
      mon:
        role: 'ceph_mon'
      mds:
        role: 'ceph_mds'
      network:
        public:
          cidr:
            - '10.1.100.0/24'
        cluster:
          cidr:
            - '10.1.100.0/24'
      osd:
        role: 'ceph_osd'
        crush:
          chooseleaf_type: 0
          update: true
        devices:
          -
            data: '/dev/sdd1'
            block_db: '/dev/sdb1'
            block_wal: '/dev/sdc1'
          -
            data: '/dev/sde1'
            block_db: '/dev/sdb2'
            block_wal: '/dev/sdc2'
          -
            data: '/dev/sdf1'
            block_db: '/dev/sdb3'
            block_wal: '/dev/sdc3'
    ceph_test:
      openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
      openstack_username: <%= ENV['OS_USERNAME'] %>
      openstack_api_key: <%= ENV['OS_PASSWORD'] %>
      openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>

suites:
  - name: default
    run_list:
      - recipe[osl-ceph]
      - recipe[ceph_test::ceph_keyring]
  - name: mon
    run_list:
      - role[ceph_mon]
  - name: mgr
    run_list:
      - role[ceph_mon]
      - role[ceph_mgr]
  - name: mds
    run_list:
      - recipe[ceph_test]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - recipe[ceph_test::osd]
      - role[ceph_mds]
      - recipe[ceph_test::mds]
  - name: osd
    run_list:
      - recipe[ceph_test]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
  - name: monitoring
    run_list:
      - recipe[osl-ceph::monitoring]
      - recipe[ceph_test::docker]
  - name: nagios
    run_list:
      - recipe[osl-ceph::nagios]
