---
verifier:
  name: inspec

driver:
  name: openstack
  flavor_ref: 'm1.large'
  user_data: userdata.txt

driver_config:
  server_name: node1

provisioner:
  name: chef_zero
  roles_path: test/integration/roles
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  attributes:
    yum:
      epel:
        baseurl: http://epel.osuosl.org/7/$basearch
        gpgkey: http://epel.osuosl.org/RPM-GPG-KEY-EPEL-7
    ceph:
      fsid-secret: ae3f1d03-bacd-4a90-b869-1a4fabb107f2
      keyring:
        mon: '/etc/ceph/$cluster.mon.keyring'

suites:
  - name: default
    run_list:
      - recipe[osl-ceph]
      - recipe[ceph_test::ceph_keyring]
  - name: mon
    run_list:
      - role[ceph]
      - role[ceph_mon]
  - name: mgr
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
  - name: mds
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - role[ceph_mds]
      - recipe[ceph_test::mds]
  - name: osd
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
  - name: monitoring
    run_list:
      - role[ceph]
      - role[ceph_mon]
      - role[ceph_mgr]
      - role[ceph_osd]
      - recipe[osl-ceph::monitoring]
      - recipe[ceph_test::monitoring]
  - name: nagios
    run_list:
      - recipe[osl-ceph::nagios]
