AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - 'metadata.rb'
    - 'cookbooks/**/*'

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Metrics/BlockLength:
  Enabled: false
