name             'osl-ceph'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
chef_version     '>= 16.0'
issues_url       'https://github.com/osuosl-cookbooks/osl-ceph/issues'
source_url       'https://github.com/osuosl-cookbooks/osl-ceph'
description      'Installs/Configures osl-ceph'
version          '4.2.0'

depends          'base'
depends          'ceph-chef', '~> 3.0.0'
depends          'git'
depends          'osl-firewall'
depends          'osl-nrpe'

supports         'centos', '~> 7.0'
